# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/book_details
    username: root
    password: ttianjun

# Logger Config
logging:
  level:
    com:
      graphqljava:
        tutorial:
          bookdetails: debug